name: Test Python Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    paths:
      - "*.py"

jobs:
  test-python:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.11' ]
      fail-fast: false
    container:
      image: python:${{ matrix.python-version }}-bullseye
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .
        pip install pytest
    - name: Test with pytest
      run: |
        pytest
